workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        CERTIFICATE_PASSWORD: Envs.CERTIFICATE_PASSWORD

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa --export-method ad-hoc

    artifacts:
      - build/ios/ipa/*.ipa
