workflows:
  ios-release:
    name: iOS Release Signed
    environment:
      flutter: stable
      xcode: latest
      vars:
        CERTIFICATE_PASSWORD: Envs.CERTIFICATE_PASSWORD

    code_signing:
      ios:
        distribution_certificate:
          certificate: $CM_CERTIFICATE
          certificate_password: $CERTIFICATE_PASSWORD
        provisioning_profile:
          profile: $CM_PROVISIONING_PROFILE

    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --export-method ad-hoc

    artifacts:
      - build/ios/ipa/*.ipa
